// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("API.Models.StationInformation", b =>
                {
                    b.Property<string>("StationId")
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("Relational:JsonPropertyName", "station_id");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "capacity");

                    b.Property<double>("Latitude")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "lat");

                    b.Property<double>("Longitude")
                        .HasColumnType("double")
                        .HasAnnotation("Relational:JsonPropertyName", "lon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "region_id");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "short_name");

                    b.HasKey("StationId");

                    b.ToTable("StationInformations");
                });
#pragma warning restore 612, 618
        }
    }
}
